### ISSUE TITLE
CRAN Check Failure for Upcoming broom Release

### ISSUE THREAD

**Issue by simonpcouch** [business-science/sweep#14]
Hi there! The broom dev team just ran reverse dependency checks on the upcoming broom 0.7.0 release and found new errors/test failures for the CRAN version of this package, which seem to result from our decision to no longer export...
* the `finish_glance()` function, in favor of adding more specific calls to `stats::BIC()` et al. (see [this issue](https://github.com/tidymodels/broom/pull/597))
* rowwise dataframe tidiers (for maintainability purposes)

I've pasted the results below:

*   checking examples ... ERROR
    ```
    ...
    
    The following objects are masked from ‘package:base’:
    
        intersect, setdiff, setequal, union
    
    > library(forecast)
    Warning: package ‘forecast’ was built under R version 3.6.2
    > library(sweep)
    > 
    > fit_arima <- WWWusage %>%
    +     auto.arima()
    > 
    > sw_tidy(fit_arima)
    [90m# A tibble: 2 x 2[39m
      term  estimate
      [3m[90m<chr>[39m[23m    [3m[90m<dbl>[39m[23m
    [90m1[39m ar1      0.650
    [90m2[39m ma1      0.526
    > sw_glance(fit_arima)
    Error: 'finish_glance' is not an exported object from 'namespace:broom'
    Execution halted
    ```

*   checking tests ...
    ```
     ERROR
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
      [90m 2. [39msweep:::sw_glance.robets(fit_robets)
      [90m 6. [39mbroom::finish_glance
      [90m 7. [39mbase::getExportedValue(pkg, name)
      
      ══ testthat results  ═══════════════════════════════════════════════════════════
      [ OK: 143 | SKIPPED: 0 | WARNINGS: 1 | FAILED: 6 ]
      1. Error: sw_sweep test returns tibble with correct rows and columns. (@test_sw_sweep.R#156) 
      2. Error: sw_*.Arima test returns tibble with correct rows and columns. (@test_tidiers_arima.R#19) 
      3. Error: sw_*.ets test returns tibble with correct rows and columns. (@test_tidiers_ets.R#19) 
      4. Failure: sw_*.default test returns tibble with correct rows and columns. (@test_tidiers_lm.R#22) 
      5. Failure: sw_*.default test returns tibble with correct rows and columns. (@test_tidiers_lm.R#32) 
      6. Error: sw_*.robets test returns tibble with correct rows and columns. (@test_tidiers_robets.R#19) 
      
      Error: testthat unit tests failed
      Execution halted
    ```

*   checking Rd cross-references ... WARNING
    ```
    Missing link or links in documentation object 'sw_augment.Rd':
      ‘rowwise_df_tidiers’
    
    See section 'Cross-references' in the 'Writing R Extensions' manual.
    ```

We hope to submit this new version of the package to CRAN in the coming weeks. If you encounter any problems fixing these issues, please feel free to reach out!🙂

**Comment by simonpcouch** [comment]
Hey Matt! I appreciate you making those changes.

Wanted to check in on your timeline for submitting 0.2.3 to CRAN—we're still seeing revdep failures on the CRAN version, but looks like your main dev branch is good to go. :-)

**Comment by mdancho84** [comment]
Hey Simon,

Yes - We are good to go. Just let me know when CRAN accepts the new broom 0.7.0. I'll send the new version of sweep to CRAN. 

-Matt

**Comment by simonpcouch** [comment]
Just as surprised about this timing as you will probably be, but 0.7.0 is now on CRAN! Much appreciated!

**Comment by mdancho84** [comment]
sweep 0.2.3 is on CRAN.
